name: reddit
description: A Reddit library for Dart.
version: 0.3.1
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-reddit
dependencies:
  http: ">=0.11.1+3 <0.12.0"
  json_object: ">=1.0.18+2 <2.0.0"
  logging: ">=0.9.3 <0.10.0"
  oauth2: ">=0.9.3 <0.10.0"
dev_dependencies:
  unittest: any
