name: reddit
description: A Reddit library for Dart.
version: 0.0.1
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-reddit
dependencies:
  http: any
  json_object: any
  logging: any
dev_dependencies:
  unittest: any
